// src/components/RecipeCard.tsx
// RecipeCard.tsx
import React from "react";
import { RecipeCardProps } from "../types/recipes";

const RecipeCard: React.FC<RecipeCardProps> = ({ recipe }) => {
    const truncateText = (text: string, maxLength: number) => {
        if (text.length <= maxLength) {
            return text;
        }
        return text.slice(0, maxLength) + "...";
    };

    return (
        <div className="book-page">
            <div className="left-page">
                <h2>{recipe.title}</h2>
                <p>(Servings: {recipe.servings})</p>
                <h3>Ingredients</h3>
                <ul>
                    {recipe.ingredients.map((ingredient, index) => (
                        <li key={index}>
                            <b>
                                {ingredient.quantity}{" "}
                                {ingredient.unit ? ingredient.unit : ""}
                            </b>{" "}
                            {ingredient.name}
                        </li>
                    ))}
                </ul>
            </div>

            <div className="right-page">
                <h2>Instructions</h2>
                <ol>
                    <li key={recipe.id}>
                        {truncateText(recipe.instructions, 300)}
                    </li>
                </ol>
                <h3>Notes</h3>
                <ol>
                    <li key={recipe.id}>{truncateText(recipe.notes, 300)}</li>
                </ol>
            </div>
        </div>
    );
};

export default RecipeCard;

// src/components/RecipeCard.svelte
<script>
	export let recipe;

	/**
	 * Truncate text to a specified length and add ellipsis if truncated.
	 * @param {string} text - The text to be truncated.
	 * @param {number} [maxLength=370] - The maximum length of the text.
	 * @return {string} The truncated text with ellipsis if it exceeds maxLength.
	 */
	// function truncateText(text, maxLength = 370) {
	// 	if (text.length > maxLength) {
	// 		return text.substring(0, maxLength) + '...';
	// 	}
	// 	return text;
	// }
</script>

<div class="book">
	<div class="left-page">
		<h2>{recipe.title}</h2>
		<p>(Servings: {recipe.servings})</p>
		<h3>Ingredients</h3>
		<ul>
			{#each recipe.ingredients as ingredient}
				<li>
					<b>{ingredient.quantity} {ingredient.unit ? ingredient.unit : ''}</b>
					{ingredient.optional ? '(optional)' : ''}
				</li>
			{/each}
		</ul>
	</div>

	<div class="right-page">
		<h2>Instructions</h2>
		<ol>
			{#each recipe.instructions as instruction}
				<!-- <li>{truncateText(instruction)}</li> -->
			{/each}
		</ol>
		<h3>Notes</h3>
		<ul>
			{#each recipe.notes as note}
				<!-- <li>{truncateText(note)}</li> -->
			{/each}
		</ul>
	</div>
</div>
